# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期，一天
  expireTime: 60 * 60 * 24

  # Spring框架配置
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-cbbmajng.sql.tencentcdb.com:24095/chatroom  # 数据库连接URL
    username: root  # 数据库用户名
    password: Banxing4116  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名
  servlet:
    multipart:
      max-file-size: 2MB  # 文件上传的最大大小限制
      max-request-size: 5MB  # 请求的最大大小限制
  data:
    redis:
      host: localhost  # Redis 主机地址
      port: 6379  # Redis 端口号
      database: 1  # Redis 数据库索引编号

  # MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # MyBatis-Plus日志实现方式
  global-config:
    db-config:
      logic-delete-field: delFlag  # 逻辑删除字段名
      logic-delete-value: 1  # 逻辑删除标识值
      logic-not-delete-value: 0  # 非逻辑删除标识值
      id-type: auto  # 主键策略